import { type Metadata } from 'next'
import {
    ClerkProvider,
    SignInButton,
    SignUpButton,
    SignedIn,
    SignedOut,
    UserButton,
} from '@clerk/nextjs'
// import { Geist, Geist_Mono } from 'next/font/google'

export const metadata: Metadata = {
    title: 'Clerk Next.js Quickstart',
    description: 'Generated by create next app',
}

export default function Authentication() {
    return (
        <ClerkProvider>
              <SignedOut>
                <div className="flex items-center">
                  {/* Login */}
                  <div className="relative group">
                    <SignInButton>
                      <div className="text-[#38b6ff] text-[16px] cursor-pointer pr-2 py-2 rounded-md 
                        transition-all duration-300 group-hover:font-bold">
                        Login
                      </div>
                    </SignInButton>
                    <div className="absolute bottom-0 left-0 w-0 h-[2px] bg-[#38b6ff] group-hover:w-full transition-all duration-300"></div>
                  </div>

                  {/* Sign Up */}
                  <div className="relative group">
                    <SignUpButton>
                      <div className="text-[#38b6ff] text-[16px] cursor-pointer px-4 py-0 rounded-md 
                        transition-all duration-300 group-hover:font-bold">
                        Sign Up
                      </div>
                    </SignUpButton>
                    <div className="absolute bottom-0 left-0 w-0 h-[2px] bg-[#38b6ff] group-hover:w-full transition-all duration-300"></div>
                  </div>
                </div>
              </SignedOut>

              <SignedIn>
                <UserButton />
              </SignedIn>
            </ClerkProvider>
    )
}