"use client"

import { type Metadata } from 'next'
import {
    ClerkProvider,
    SignInButton,
    SignUpButton,
    SignedIn,
    SignedOut,
    UserButton,
} from '@clerk/nextjs'

export const metadata: Metadata = {
    title: 'Clerk Next.js Quickstart',
    description: 'Generated by create next app',
}

// import Image from "next/image";
import Link from "next/link";
import Dropdown from "./component/dropdown";
import Sidebar from "./component/sidebar";
// import arrow from "../../public/images/icons8-arrow-96.png";
import downarrow from "../../public/images/icons8-chevron-96.png";

function Navbar() {
  return (
    <>
      {/* Top Bar */}
      <div className="bg-[#2c2c2c] text-white">
        <div className="flex gap-5 text-[10px] sm:text-[12px] customize-max-width justify-end py-2 animate__animated animate__fadeInDown">
          <div className="hover:text-[#38b6ff] transition-colors duration-300 cursor-pointer">
            email1234@gmail.com
          </div>
          <div className="hover:text-[#38b6ff] transition-colors duration-300 cursor-pointer">
            0300-0000000
          </div>
        </div>
      </div>

      {/* Main Navbar */}
      <div className="bg-gradient-to-r from-[#0F2027] via-[#203A43] to-[#2C5364]">
        <div className="customize-max-width px-4 sm:px-0 mx-auto flex justify-between items-center text-black py-3 animate__animated animate__fadeIn">
          {/* Logo */}
          <div className="text-[25px] font-bold text-[#38b6ff] tracking-wide hover:font-bold transition-all duration-300 cursor-pointer">
            Logo
          </div>

          {/* Menu Items */}
          <div className="sm:flex gap-6 items-center hidden">
            {/* Normal Links */}
            {[
              { href: "/", label: "Home" },
              { href: "/client-portal", label: "Client Portal" },
              { href: "/engineer-portal", label: "Engineer Portal" },
              { href: "/aboutus", label: "About Us" },
              { href: "/contact", label: "Contact Us" },
            ].map((item) => (
              <div key={item.href} className="relative group">
                <Link
                  href={item.href}
                  className="text-[#38b6ff] hover:font-bold transition-all duration-300 text-[16px]"
                >
                  {item.label}
                </Link>
                <div className="absolute bottom-0 left-0 w-0 h-[2px] bg-[#38b6ff] group-hover:w-full transition-all duration-300"></div>
              </div>
            ))}

            {/* Dropdown */}
            <div className="relative group">
              <Dropdown imageSrc={downarrow} />
              <div className="absolute bottom-0 left-0 w-0 h-[2px] bg-[#38b6ff] group-hover:w-full transition-all duration-300"></div>
            </div>

            {/* Authentication Buttons */}
            <ClerkProvider>
              <SignedOut>
                <div className="flex items-center">
                  {/* Login */}
                  <div className="relative group">
                    <SignInButton>
                      <div className="text-[#38b6ff] text-[16px] cursor-pointer pr-2 py-2 rounded-md 
                        transition-all duration-300 group-hover:font-bold">
                        Login
                      </div>
                    </SignInButton>
                    <div className="absolute bottom-0 left-0 w-0 h-[2px] bg-[#38b6ff] group-hover:w-full transition-all duration-300"></div>
                  </div>

                  {/* Sign Up */}
                  <div className="relative group">
                    <SignUpButton>
                      <div className="text-[#38b6ff] text-[16px] cursor-pointer pl-4 py-0 rounded-md 
                        transition-all duration-300 group-hover:font-bold">
                        Sign Up
                      </div>
                    </SignUpButton>
                    <div className="absolute bottom-0 left-0 w-0 h-[2px] bg-[#38b6ff] group-hover:w-full transition-all duration-300"></div>
                  </div>
                </div>
              </SignedOut>

              <SignedIn>
                <UserButton />
              </SignedIn>
            </ClerkProvider>
          </div>

          {/* Sidebar for mobile */}
          <div className="sm:hidden">
            <Sidebar />
          </div>
        </div>
      </div>
    </>
  );
}

export default Navbar;